apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  labels:
    target-allocation: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: kube-state-metrics

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-state-metrics
  template:
    metadata:
      labels:
        app: kube-state-metrics
    spec:
      serviceAccountName: kube-state-metrics
      containers:
        - name: kube-state-metrics
          image: bitnami/kube-state-metrics:latest
          ports:
            - containerPort: 8080
          args:
            - --port=8080
            - --telemetry-port=8081