extensions:
  sigv4auth:
    region: ap-southeast-1
    service: aps

receivers:
  prometheus:
    config:
      global:
        scrape_interval: 15s
      scrape_configs:
        - job_name: 'weather-api'
          static_configs:
            - targets: ['weather-api:5170']
        - job_name: 'payment-api'
          static_configs:
            - targets: ['payment-api:5180']
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['cadvisor:8080']

  otlp:
    protocols:
      http:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  awsxray:
    region: ap-southeast-1
    no_verify_ssl: false
  prometheusremotewrite:
    endpoint: ${PROM_REMOTE_WRITE}
    auth:
      authenticator: sigv4auth

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus, prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [awsxray]