extensions:
  sigv4auth:
    region: ap-southeast-1
    service: aps

receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'weather-api'
          static_configs:
            - targets: ['weather-api:5170']
        - job_name: 'payment-api'
          static_configs:
            - targets: ['payment-api:5180']
        - job_name: 'node-exporter'
          static_configs:
            - targets: ['node-exporter:9100']
        - job_name: 'cadvisor'
          static_configs:
            - targets: ['cadvisor:8080']

  otlp:
    protocols:
      http:
      grpc:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheusremotewrite:
    endpoint: https://aps-workspaces.ap-southeast-1.amazonaws.com/workspaces/ws-8f238eef-b22a-4b6b-b6b0-f669e33105b4/api/v1/remote_write
    auth:
      authenticator: sigv4auth

service:
  extensions: [sigv4auth]
  pipelines:
    metrics:
      receivers: [prometheus]
      exporters: [prometheus, prometheusremotewrite]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]