auth_enabled: false

server:
  http_listen_address: 0.0.0.0
  http_listen_port: 3200
  grpc_listen_port: 9095
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 1
    join_after: 0s
    min_ready_duration: 5s
    final_sleep: 0s
  trace_idle_period: 10s
  max_block_duration: 5m

memberlist:
  bind_port: 7946
  join_members:
    - tempo-distributor:7946
    - tempo-ingester:7946
    - tempo-querier:7946
    - tempo-query-frontend:7946
    - tempo-metrics-generator:7946

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

compactor:
  compaction:
    block_retention: 1h

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: my-cluster
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://host.docker.internal:9090/api/v1/write
        send_exemplars: true
overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics

query_frontend:
  search:
    duration_slo: 5s
  trace_by_id:
    duration_slo: 5s

querier:
  frontend_worker:
    frontend_address: tempo-query-frontend:9095 # (Neeeded) Grafana doesn’t talk directly to the querier. Instead, it sends trace queries to Tempo’s Query Frontend
