apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5180"
    prometheus.io/path: /metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
      - name: payment-api
        image: payment-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5180
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api-service
spec:
  type: NodePort
  selector:
    app: payment-api
  ports:
  - port: 5180
    targetPort: 5180
    nodePort: 30180  # External port (30000-32767 range)