apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  type: NodePort
  selector:
    app: otel-collector
  ports:
    - protocol: TCP
      port: 8889
      targetPort: 8889
      nodePort: 30089
