apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-api-monitor
  namespace: default
spec:
  endpoints:
  - interval: 30s
    targetPort: 5170
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      target-allocation: "true"