apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubemetrics-monitor
  namespace: default
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      target-allocation: "true"